### ISSUE TITLE
Graufläche anstelle Verbrauchschart

### ISSUE THREAD

**Issue by timobaehr** [ehwplus/app-backlog#333]
getAverageDataFromRange sollte nie Haushaltsgröße 0 zurückgeben, auch wenn man über die Pfeiltaste von 1 auf 0 heruntergedreht hat.

Daten:
```json
    "houseHoldSize": {
        "2024-02-10T00:00:00.000": {
            "value": 3,
            "comment": null
        },
        "null": {
            "value": 0,
            "comment": null
        }
    }
```

**Null check operator used on a null value**
```
  ConsumptionChart ConsumptionChart:file:///Users/timo/Projekte/private/ehwplus_app/lib/counter/counter_entries/counter_statistics_view_mixin.dart:46:26
When the exception was thrown, this was the stack: 
#0      _ConsumptionChartState.horizontalLines (package:energy_tracker/chart/time_series_line_chart/consumption_chart.dart:692:39)
#1      _ConsumptionChartState.build (package:energy_tracker/chart/time_series_line_chart/consumption_chart.dart:123:38)
```

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/2582

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/2573

**Comment by timobaehr** [comment]
`1.12.10`
