### ISSUE TITLE
Excel-Export schlägt fehl mit Fehlermeldung "Cannot remove from an unmodifiable list"

### ISSUE THREAD

**Issue by timobaehr** [ehwplus/app-backlog#513]
Excel-Export mit dem Package [excel](https://pub.dev/packages/excel) Version 4.0.2 schlägt fehl mit Fehlermeldung "Cannot remove from an unmodifiable list".

Die aktuellste Version ist 4.0.6.

```
>> Stacktrace >> 
2      _Share._shareExcelFile.<anonymous closure> (package:energy_tracker/screens/import_export/export_tab.dart:324:17)
<asynchronous suspension>

[log] [error] [2024-11-16 07:57:20] Received uncaught error: Unsupported operation: Cannot remove from an unmodifiable list with stacktrace
#0      UnmodifiableListMixin.removeWhere (dart:_internal/list.dart:139:5)
#1      Excel.delete (package:excel/src/excel.dart:279:22)
#2      Excel.rename (package:excel/src/excel.dart:213:7)
#3      ExcelManager.create (package:energy_tracker/import_export_sync/excel_manager.dart:23:40)
#4      _Share._convertObjectIntoExcelBytes (package:energy_tracker/screens/import_export/export_tab.dart:488:48)
#5      _Share._shareExcelFile.<anonymous closure> (package:energy_tracker/screens/import_export/export_tab.dart:309:35)
#6      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1170:21)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:351:24)
```

**Comment by timobaehr** [comment]
https://support.ehwplus.com/#ticket/zoom/3251
